[build]
  publish = "."
  functions = "netlify/functions"
  command = "cd netlify/functions && npm install"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
